# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build helloworld
      working-directory: ./npm-helloworld
      run: npm ci && npm test
    - name: Pack helloworld
      working-directory: ./npm-helloworld
      run: npm pack
    - name: Re-create package-lock.json (because of checksum issues with the Tarball)
      working-directory: ./npm-myapp
      run: rm -f package-lock.json && npm install
    - name: Run myapp
      working-directory: ./npm-myapp
      run: npm start
